version: "3"

tasks:
  default:
    deps: [install]

  install:
    desc: Install the package in development mode
    cmds:
      - uv pip install -e --group dev .

  build:
    desc: Build distribution packages
    cmds:
      - rm -rf dist
      - uv build

  test-pypi:
    desc: Upload source distribution to TestPyPI (requires UV_PUBLISH_TOKEN or --token)
    cmds:
      - uv publish --publish-url https://test.pypi.org/legacy/ dist/*.tar.gz

  clean:
    desc: Remove compiled files
    cmds:
      - rm -rf src/*.o src/*.so

  test:
    desc: Run all tests
    cmds:
      - pytest
      - cd docs && make doctest

  docs:
    desc: Build documentation
    dir: docs
    cmds:
      - make html

  autodoc:
    desc: Auto-build documentation on changes
    cmds:
      - sphinx-autobuild docs/source docs/build --watch sortedl1
