version: "3"

vars:
  LIBSLOPE_API_URL: https://api.github.com/repos/jolars/libslope/releases/latest
  LIBSLOPE_RELEASE:
    sh: curl -s {{.LIBSLOPE_API_URL}} | grep "tarball_url" | cut -d '"' -f 4

tasks:
  default:
    deps: [install]

  install:
    desc: Install the package in development mode
    cmds:
      - pip install -e .[tests,docs]

  build:
    desc: Build distribution packages
    cmds:
      - rm -rf dist
      - python -m build

  test-pypi:
    desc: Upload packages to TestPyPI
    cmds:
      - python -m twine upload --repository testpypi dist/*.tar.gz

  clean:
    desc: Remove compiled files
    cmds:
      - rm -rf src/*.o src/*.so

  test:
    desc: Run all tests
    cmds:
      - pytest
      - cd docs && make doctest

  docs:
    desc: Build documentation
    dir: docs
    cmds:
      - make html

  autodoc:
    desc: Auto-build documentation on changes
    cmds:
      - sphinx-autobuild docs/source docs/build --watch sortedl1

  update-libslope:
    desc: Fetch and update the latest libslope release
    vars:
      VERSION:
        sh: gh release view --repo jolars/libslope --json tagName --jq .tagName
    cmds:
      - echo "Fetching latest libslope release..."
      - mkdir -p tmp
      - gh release download --repo jolars/libslope --dir tmp/ --archive=tar.gz --clobber
      - cd tmp && tar xzf *.tar.gz
      - rm -rf src/slope
      - mkdir -p src/slope
      - cp -r tmp/*/src/slope/* src/slope/
      - echo "# WARNING! DO NOT MODIFY FILES IN THIS DIRECTORY" >> src/slope/DO_NOT_MODIFY
      - echo "# These files are automatically updated from https://github.com/jolars/libslope" >> src/slope/DO_NOT_MODIFY
      - rm -rf tmp
      - git add src/slope
      - 'git commit -m "feat: update libslope to {{.VERSION}}" -m "Release: https://github.com/jolars/libslope/releases/tag/{{.VERSION}}"'
    silent: true

  update-eigen:
    desc: Fetch and update the latest Eigen library
    vars:
      EIGEN_VERSION:
        sh: curl -s https://gitlab.com/api/v4/projects/libeigen%2Feigen/releases | jq -r '.[0].tag_name'
    cmds:
      - echo "Fetching Eigen {{.EIGEN_VERSION}}..."
      - mkdir -p tmp
      - curl -L https://gitlab.com/libeigen/eigen/-/archive/{{.EIGEN_VERSION}}/eigen-{{.EIGEN_VERSION}}.tar.gz -o tmp/eigen.tar.gz
      - cd tmp && tar xzf eigen.tar.gz
      - rm -rf external/Eigen
      - mkdir -p external
      - cp -r tmp/eigen-*/Eigen external/
      - rm -rf tmp
      - git add external/Eigen
      - 'git commit -m "feat: update Eigen to {{.EIGEN_VERSION}}" -m "Source: https://gitlab.com/libeigen/eigen/-/releases/{{.EIGEN_VERSION}}"'
    silent: true
